"""initial civic issue table

Revision ID: 532d72275ef2
Revises: 
Create Date: 2025-06-28 09:29:30.393850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532d72275ef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civic_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('civic_issue')
    # ### end Alembic commands ###
